### ISSUE TITLE
Error when running generator

### ISSUE THREAD

**Issue by pipozoft** [frontend/generator-toolbox#16]
I'm getting this error when I'm tying to run `yo toolbox`

```
module.js:341
    throw err;
    ^

Error: Cannot find module 'unicode/category/So'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at symbols (/usr/lib/node_modules/generator-toolbox/node_modules/slug/slug.js:6:16)
    at /usr/lib/node_modules/generator-toolbox/node_modules/slug/slug.js:199:5
    at Object.<anonymous> (/usr/lib/node_modules/generator-toolbox/node_modules/slug/slug.js:212:2)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
```

Any ideas? 

Thanks

**Comment by Yago** [comment]
Hi @pipozoft !

Which NodeJS/NPM version have you ?

**Comment by pipozoft** [comment]
node -v  v5.7.0
npm -v  3.6.0

@Yago that's what I'm using

**Comment by Yago** [comment]
It seems that **slug.js** is the problem. We use it to fits your project's name with the package.json name format. Try with a simple name, maybe it will solve your issue :sweat_smile:

**Comment by pipozoft** [comment]
@Yago I tried `yo toolbox test` and it fails with the same error :/

**Comment by WengerK** [comment]
@pipozoft  Get the same issue, using version of Node7 or less.

For now, it only works with Node8+.
We added this informations on the documentation. 

https://frontend.github.io/toolbox/getting-started/
> Before you can run the generator, you need to make sure you have the latest version of Yeoman installed and Node v8 installed.

Let us know if you get another issue after upgrading your node version.
