### ISSUE TITLE
Can we avoid `python` dependencies ?

### ISSUE THREAD

**Issue by gido** [frontend/generator-toolbox#42]
Some the default dependencies package require to build something with python.
Do you think we can avoid this dependency ?

```
$ npm install

> buffertools@2.1.4 install C:\Projects\styleguide\node_modules\buffertools
> node-gyp rebuild


C:\Projects\styleguide\node_modules\buffertools>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:401:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:356:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Projects\styleguide\node_modules\buffertools
gyp ERR! node -v v6.5.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
```

**Comment by tonifisler** [comment]
@gido `node-gyp` is required by `node-sass` :(

``` shell
toolbox@0.0.0 /Users/toni/Sites/test
└─┬ gulp-sass@2.3.2
  └─┬ node-sass@3.10.0
    └── node-gyp@3.4.0
```
